### PR TITLE
implement geo-tags on index page

### PR DESCRIPTION
**Pull request by iamstarkov**
@kinday pls, take a look
screen shot 2015-10-02 at 16 10 50

### CODE REVIEW

**Comment by kinday** [comment]
Formalized data would look better, wouldn’t it? Also drop invalid (and empty) values or ask authors to provide them.

**Comment by iamstarkov** [comment]
empty and invalid data already droped in https://github.com/iamstarkov/jsunderhood/commit/fa9cdfa402f661c3e743bb7a4d6c2b7387b12d95

**Comment by iamstarkov** [comment]
dont get about formalized data, its just this field https://github.com/iamstarkov/jsunderhood/blob/master/dump/RReverser-info.json#L6

**Comment by kinday** [comment]
City and country. In Russian. “Planet Earth” sounds like a bad joke and must be treated as invalid.

We may edit it manually for existing archives and ask authors to set their location in required form in future.

**Comment by iamstarkov** [comment]
as you already know, i dont like manual labor. If author decided to have a bad joke and its acceptable by code of conduct, I assume that it is intended by author as part of their week experience for readers, so im assuming its fine. what do you think?

**Comment by kinday** [comment]
I think you are the law-maker.

People tend to love user-generated content, because they can lean back and watch a project develops itself. I think UGC needs editing (or set of rules) to shine.

This issue doesn’t look like a good place for philosophic discussions. We can talk on it later.

Make a quick decision. There’s no big deal.

**Pull request merged**
